version: 2
updates:
  - package-ecosystem: "github-actions"
    target-branch: main
    schedule:
      interval: "weekly"
    directory: "/"
    labels:
      - dependabot
    commit-message:
      prefix: BAU
  - package-ecosystem: "gradle"
    target-branch: main
    schedule:
      interval: "weekly"
    directory: "/integration-tests"
    labels:
      - dependabot
    commit-message:
      prefix: BAU
  - package-ecosystem: "npm"
    target-branch: main
    schedule:
      interval: daily
      time: "02:52"
    directories:
      - "/"
    labels:
      - dependabot
    commit-message:
      prefix: BAU
    groups:
      aws:
        patterns:
          - "@aws-*"
      eslint:
        patterns:
          - "eslint"
          - "eslint-*"
          - "@typescript-eslint/*"
