name: Post merge

on:
  pull_request:
    types:
      - closed

permissions:
  id-token: write
  contents: read

jobs:
  delete-preview-stack:
    name: Delete preview stack
    runs-on: ubuntu-latest
    environment: integration-tests
    steps:
      - name: Get stack name
        uses: govuk-one-login/github-actions/beautify-branch-name@ca188729ecb0c92e5fe5ae7c024f9894815da3a1
        id: get-stack-name
        with:
          usage: Stack name
          prefix: preview-common-lambdas
          length-limit: 37
          verbose: false

      - name: Delete stack
        uses: govuk-one-login/github-actions/sam/delete-stacks@ca188729ecb0c92e5fe5ae7c024f9894815da3a1
        with:
          stack-names: ${{ steps.get-stack-name.outputs.pretty-branch-name }}
          aws-role-arn: ${{ vars.DEPLOYMENT_ROLE_ARN }}
          verbose: true
