name: Pre-merge integration test
on:
  pull_request:
    types:
      - opened
      - reopened
      - ready_for_review
      - synchronize

jobs:
  deploy:
    name: pre-merge-integration-tests
    runs-on: ubuntu-latest
    environment: di-ipv-cri-dev
    timeout-minutes: 15
    env:
      AWS_REGION: eu-west-2
      ENVIRONMENT: dev
      STACK_NAME_PREFIX: pre-merge-integration
      SECRET_PREFIX: pre-merge-test
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: zulu

      - name: Setup SAM
        uses: aws-actions/setup-sam@v2

      - name: Assume temporary AWS role
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: ${{ secrets.GH_ACTIONS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: SAM build
        run: sam build -t infrastructure/lambda/template.yaml

      - name: Set short SHA
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: SAM deploy integration test stack
        run: |
          STACK_NAME=${{ env.STACK_NAME_PREFIX }}-${{ steps.vars.outputs.sha_short }}
          sam deploy --stack-name "$STACK_NAME" \
          --no-fail-on-empty-changeset \
          --no-confirm-changeset \
          --s3-bucket ${{ secrets.AWS_CONFIG_BUCKET }} \
          --region eu-west-2 \
          --capabilities CAPABILITY_IAM \
          --parameter-overrides \
          CodeSigningEnabled=false \
          Environment=${{ env.ENVIRONMENT }} \
          AuditEventNamePrefix=/common-cri-parameters/AuditEventNamePrefix \
          CriIdentifier=/common-cri-parameters/CriIdentifier

      - name: Run API integration tests
        env:
          IPV_CORE_STUB_URL: https://di-ipv-core-stub.london.cloudapps.digital
          IPV_CORE_STUB_BASIC_AUTH_USER: ${{ secrets.IPV_CORE_STUB_BASIC_AUTH_USER }}
          IPV_CORE_STUB_BASIC_AUTH_PASSWORD: ${{ secrets.IPV_CORE_STUB_BASIC_AUTH_PASSWORD }}
          PUBLIC_API_KEY: ${{ secrets.API_KEY_CRI_DEV }}
        run: |
          STACK_NAME=${{ env.STACK_NAME_PREFIX }}-${{ steps.vars.outputs.sha_short }}
          API_GATEWAY_ID_PRIVATE=$(aws cloudformation describe-stacks --stack-name $STACK_NAME | jq -r '.Stacks[].Outputs[] | select(.OutputKey == "PreMergeDevOnlyApiId").OutputValue')
          export API_GATEWAY_ID_PRIVATE=$API_GATEWAY_ID_PRIVATE
          gradle integration-tests:cucumber

      - name: Delete integration test stack
        if: success()
        run: |
          STACK_NAME=${{ env.STACK_NAME_PREFIX }}-${{ steps.vars.outputs.sha_short }}
          aws cloudformation delete-stack --region ${{ env.AWS_REGION }} --stack-name $STACK_NAME
